//
//  File.swift
//  
//
//  Created by Clayton Sulby on 6/25/23.
//

import Foundation

enum PlayPaths : String, CaseIterable {
    
    case alls_well_that_ends_well = "ps_alls_well_that_ends_well"
    case antony_cleopatra = "ps_antony_cleopatra"
    case as_you_like_it = "ps_as_you_like_it"
    case comedy_of_errors = "ps_comedy_of_errors"
    case coriolanus = "ps_coriolanus"
    case cymbeline = "ps_cymbeline"
    case hamlet = "ps_hamlet"
    case henry_iv_pt1 = "ps_henry_iv_pt1"
    case henry_iv_pt2 = "ps_henry_iv_pt2"
    case henry_v = "ps_henry_v"
    case henry_vi_pt1 = "ps_henry_vi_pt1"
    case henry_vi_pt2 = "ps_henry_vi_pt2"
    case henry_vi_pt3 = "ps_henry_vi_pt3"
    case henry_viii = "ps_henry_viii"
    case julius_caesar = "ps_julius_caesar"
    case king_john = "ps_king_john"
    case king_lear = "ps_king_lear"
    case king_richard_ii = "ps_king_richard_ii"
    case lovers_complaint = "ps_lovers_complaint"
    case loves_labours_lost = "ps_loves_labours_lost"
    case macbeth = "ps_macbeth"
    case measure_for_measure = "ps_measure_for_measure"
    case merchant_of_venice = "ps_merchant_of_venice"
    case merry_wives_of_windsor = "ps_merry_wives_of_windsor"
    case midsummer_nights_dream = "ps_midsummer_nights_dream"
    case much_ado_about_nothing = "ps_much_ado_about_nothing"
    case othello = "ps_othello"
    case passionate_pilgrim = "ps_passionate_pilgrim"
    case pericles = "ps_pericles"
    case phoenix_and_turtle = "ps_phoenix_and_turtle"
    case rape_of_lucrece = "ps_rape_of_lucrece"
    case richard_iii = "ps_richard_iii"
    case romeo_and_juliet = "ps_romeo_and_juliet"
    case sir_thomas_more = "ps_sir_thomas_more"
    case sonnets = "ps_sonnets"
    case taming_of_the_shrew = "ps_taming_of_the_shrew"
    case tempest = "ps_tempest"
    case timon_of_athens = "ps_timon_of_athens"
    case titus_andronicus = "ps_titus_andronicus"
    case to_the_queen = "ps_to_the_queen"
    case troilus_and_cressida = "ps_troilus_and_cressida"
    case twelfth_night = "ps_twelfth_night"
    case two_gentlemen_of_verona = "ps_two_gentlemen_of_verona"
    case two_noble_kinsmen = "ps_two_noble_kinsmen"
    case venus_and_adonis = "ps_venus_and_adonis"
    case winters_tale = "ps_winters_tale"
    
    //First Folio
    case winters_tale_FF = "ps_winters_tale_FF"
    case alls_well_that_ends_well_FF = "ps_alls_well_that_ends_well_FF"
    case antony_cleopatra_FF = "ps_antony_cleopatra_FF"
    case as_you_like_it_FF = "ps_as_you_like_it_FF"
    case comedy_of_errors_FF = "ps_comedy_of_errors_FF"
    case coriolanus_FF = "ps_coriolanus_FF"
    case cymbeline_FF = "ps_cymbeline_FF"
    case first_folio_frontmatter = "ps_first_folio_frontmatter"
    case hamlet_FF = "ps_hamlet_FF"
    case henry_iv_pt1_FF = "ps_henry_iv_pt1_FF"
    case henry_iv_pt2_FF = "ps_henry_iv_pt2_FF"
    case henry_v_FF = "ps_henry_v_FF"
    case henry_vi_pt1_FF = "ps_henry_vi_pt1_FF"
    case henry_vi_pt2_FF = "ps_henry_vi_pt2_FF"
    case henry_vi_pt3_FF = "ps_henry_vi_pt3_FF"
    case henry_viii_FF = "ps_henry_viii_FF"
    case julius_caesar_FF = "ps_julius_caesar_FF"
    case king_john_FF = "ps_king_john_FF"
    case king_lear_FF = "ps_king_lear_FF"
    case king_richard_ii_FF = "ps_king_richard_ii_FF"
    case loves_labours_lost_FF = "ps_loves_labours_lost_FF"
    case macbeth_FF = "ps_macbeth_FF"
    case measure_for_measure_FF = "ps_measure_for_measure_FF"
    case merchant_of_venice_FF = "ps_merchant_of_venice_FF"
    case merry_wives_of_windsor_FF = "ps_merry_wives_of_windsor_FF"
    case midsummer_nights_dream_FF = "ps_midsummer_nights_dream_FF"
    case much_ado_about_nothing_FF = "ps_much_ado_about_nothing_FF"
    case othello_FF = "ps_othello_FF"
    case richard_iii_FF = "ps_richard_iii_FF"
    case romeo_and_juliet_FF = "ps_romeo_and_juliet_FF"
    case taming_of_the_shrew_FF = "ps_taming_of_the_shrew_FF"
    case tempest_FF = "ps_tempest_FF"
    case timon_of_athens_FF = "ps_timon_of_athens_FF"
    case titus_andronicus_FF = "ps_titus_andronicus_FF"
    case troilus_cressida_FF = "ps_troilus_cressida_FF"
    case twelfth_night_FF = "ps_twelfth_night_FF"
    case two_gentlemen_of_verona_FF = "ps_two_gentlemen_of_verona_FF"
    
    //Apocrypha
    case arden_of_faversham = "ps_arden_of_faversham"
    case birth_of_merlin = "ps_birth_of_merlin"
    case double_falsehood = "ps_double_falsehood"
    case edmund_ironside = "ps_edmund_ironside"
    case edward_iii = "ps_edward_iii"
    case fair_em = "ps_fair_em"
    case funeral_elegy = "ps_funeral_elegy"
    case london_prodigal = "ps_london_prodigal"
    case merry_devil_of_edmonton = "ps_merry_devil_of_edmonton"
    case mucedorus = "ps_mucedorus"
    case puritan = "ps_puritan"
    case second_maidens_tragedy = "ps_second_maidens_tragedy"
    case sejanus = "ps_sejanus"
    case shall_i_die = "ps_shall_i_die"
    case sir_john_oldcastle = "ps_sir_john_oldcastle"
    case spanish_tragedy = "ps_spanish_tragedy"
    case thomas_lord_cromwell = "ps_thomas_lord_cromwell"
    case thomas_of_woodstock = "ps_thomas_of_woodstock"
    case tragedy_of_locrine = "ps_tragedy_of_locrine"
    case troublesome_reign_king_john = "ps_troublesome_reign_king_john"
    case yorkshire_tragedy = "ps_yorkshire_tragedy"
}
